//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

/// <summary>
/// Player controller and behavior
/// </summary>
public class MookController : MonoBehaviour
{
	/// <summary>
	/// 1 - The speed of the ship
	/// </summary>
	public Vector2 speed = new Vector2(-5, 0);
	public Vector2 waveSpeed = new Vector2(0, 1);

	public int hp = 3;

	public float stoppingDistance = 2f; //distance at which cherub stops and starts punching
	private float distanceFromPlayer;

	private GameObject player;
	
	// 2 - Store the movement
	private Vector2 movement;

	GameObject globalData;					// GameObject containing player data and HashIDs
	HashIDs hash;							// The HashIDs
	Animator animator; 						// Controls animation

	MinionGenerator generator; 

	void Awake() {
		player = GameObject.FindGameObjectWithTag("Player");
		distanceFromPlayer = Vector2.Distance(player.transform.position, transform.position);
		globalData = GameObject.FindGameObjectWithTag("GameController");
		animator = GetComponent<Animator>();
		hash = globalData.GetComponent<HashIDs>();
		generator = GameObject.FindGameObjectWithTag ("EnemyGenerator").GetComponent<MinionGenerator> ();
	}
	
	void Update()
	{
		distanceFromPlayer = Vector2.Distance(player.transform.position, transform.position);
		Fly();

		if(distanceFromPlayer <= stoppingDistance) animator.SetBool (hash.attackBool, true);
		else animator.SetBool (hash.attackBool, false);
		
	}

	void Fly() {

		// 4 - Movement per direction
		movement = new Vector2 (
			speed.x,
			speed.y + waveSpeed.y * Mathf.Sin (Time.time * 5)) / 5;
	}

	void OnTriggerEnter2D(Collider2D other) {
		if(other.gameObject.tag == "Melee")
		{
			animator.SetTrigger(hash.hurtTrigger);
			hp -= 1; //HURT ENEMY
			if(hp <= 0) Die();
		}
		
	}

	void OnTriggerStay2D(Collider2D other) {
		if(other.gameObject.tag == "Bottom")
		{
			animator.SetTrigger(hash.hurtTrigger);
			hp -= 1; //HURT ENEMY
			if(hp <= 0) { 
				Die();
				// also send message to respective god boredom bar 
			}
		}
		if (other.gameObject.tag == "Wall") {
			Die ();
		}
	}


	void Die() {
		GameObject bloodyBits = Resources.Load ("Effects/Bloody Bits") as GameObject;
		Instantiate(bloodyBits, transform.position, Quaternion.identity);
		generator.total--;
		Destroy(this.gameObject);
	}

	void FixedUpdate()
	{
		// 5 - Move the game object
		rigidbody2D.velocity = movement;
	}
}
